src/ingestion.rs
[Casing conforms to RFC 430 (C-CASE)](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case)
> In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn.
=> Make names conform to Rust API Guidelines

src/settings.rs
A user doesn't necessarily want to have an empty directory
automatically created when they have provided valid paths for the
ceritificate and key.
=> Avoid creating an empty directory

src/main.rs, src/settings.rs
If the command-line argument for the configuration file is missing,
use config.toml in the config directory instead.
=> Read config file from config dir if no path is given

src/main.rs, src/storage.rs
By parsing the retention period in `main`, `retain_periodically` can
remain independent of the format and thus be called in other context
as well.
This also allows to print a better error message when the retention
period in config contains an invalid value.
=> Make `storage::retention_periodically` format-independent

src/graphql.rs
`ConnRawEvent` contains information for a single connection only.
=> Use a singular form for type representing a single entry

src/storage.rs
The storage shouldn't provide this function because its return value would consume too much memory.
=> Remove unused function

src/graphql.rs
GraphQL API에만 쓰이는 함수, struct는 async-graphql이 생성한 코드를 통해서만 사용되므로 `pub`일 필요가 없습니다.
=> Remove unnecessary `pub`

src/graphql.rs, src/web.rs
This allows to change the GraphQL schema (e.g., adding mutations) without modifying web.rs.
=> Decouple web module from graphql

src/main.rs, src/web.rs
* Prints which of the certificate and key has the problem in read
* Prints an error message when the GraphQL server address is invalid
This also removes unnecessary `clone`s in `main`.
=> Print more specific error messages

src/storage.rs
The start time in the key should be in nanoseconds, not in seconds.
=> Correct the time unit of DNS search query

src/graphql/log.rs, src/graphql/network.rs, src/storage.rs
Replace `append` with `extend` so that the argument doesn't have to own data.
=> Remove unnecessary memory allocation

clippy.toml, src/main.rs, src/web.rs
This also removes web's dependency on rustls to avoid any confusion.
Noted by @BLYKIM in #103.
=> Document key incompatibility in `web::serve`

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/publish.rs, src/storage.rs
Pagination is required by GraphQL and should be in the graphql module.
This also fixes `hasPreviousPage` returning `true` when there is no preceding log event.
Resolves: #93
=> Move pagination logic from storage to graphql

src/graphql/log.rs, src/graphql/network.rs
여러 인자를 `filter` 하나로 대체하면서 `allow(clippy::too_many_arguments)`가 필요없게 되었습니다.
=> Remove unnecessary attribute: `allow(clippy::too_many_arguments)`

src/ingestion.rs, src/storage.rs
`RawEventStore::all_keys`는 데이터가 많은 경우 스토리지에 상당히 부하를 줄 수 있으므로, 해당 함수를 `RawEventStore`에서 제외하고, source를 관리하는 `struct SourceStore`를 따로 만들어 거기에서만 가능하도록 변경합니다. `SourceStore`는 source만을 다루므로, `SourceStore::insert`에서처럼 특화된 인터페이스(`&[u8]` 대신 `&str`, `&DateTime`을 key, value로)를 제공할 수 있는 장점도 있습니다.
=> Separate `SourceStore` from `RawEventStore`

src/server.rs
Change the data source from the issuer's cn to the subject's cn.
The subject's cn should determine the certificate's host.
=> modify cert issuer cn to subject cn

src/graphql/network.rs, src/ingestion.rs, src/ingestion/tests.rs, src/publish/tests.rs, src/storage.rs
네트워크 이벤트의 자료구조 이름을 Zeek에서 사용하는 것과 동일하게 맞춥니다.
=> Make network event names conform to Zeek's naming

CHANGELOG.md, src/publish.rs, src/publish/tests.rs
giganto가 stream을 요청받고 uni-direction channel을 open할때, 실제 데이터 전송이 없으면  hog/crusher쪽에서는 channel이 open 된것을 알 수 없습니다.(hog/crusher쪽에서는 accept_uni() 위치에 머뭄, 실제로 전송이 없으면 open이 안되는 것을 보임).이를 확인하기 위해서 요청 받은 뒤 uni-direction channel로 start message 로  protocol(u32)를 전송을 추가합니다.
=> Send stream start message to connected daemon

src/publish.rs, src/publish/tests.rs
publish 프로토콜이 0.6.0과 달라졌으므로, 0.6.0 프로토콜을 쓰는 클라이언트의 접속을 막기 위해 버전 조건을 변경합니다.
=> Bump the publish protocol version

CHANGELOG.md, src/graphql.rs, src/ingestion.rs, src/main.rs, src/publish.rs, src/settings.rs, src/storage.rs
#219 Piglet으로부터 트래픽 수집 및 저장 기능
* Receive traffic statistics from Piglet and save it to `statistics` db.
* Fix clippy error from rust 1.66
=> receive and save traffic statistics from piglet

CHANGELOG.md, giganto-client/src/ingest.rs, src/graphql/packet.rs, src/ingest.rs, src/ingest/implement.rs
- Modify ingest packet to `Vec<u8>` from `String`
- In graphql `Packets` takes `source` and `requestTime` and
optional `packetTime` range,
returns `packet`, `packetTime`, `requestTime`
Issue: #247
=> Add GraphQL API for Packets

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/packet.rs, src/ingest.rs, src/ingest/tests.rs
- Modify to deserialize packet
`giganto-client`가 적용되며 packet 데이터를 `bincode::serialize`하고 보내게 변경되어서
기존 packet data의 앞에 길이값이 추가되는 버그를 수정합니다.
=> Fix ingest::handle_data packet logic

src/ingest.rs, src/publish.rs, src/publish/tests.rs
- Change an ambiguous bool type (using enum type)
- Change `&Vec<u8>` to `&[u8]`
- Change the creation of NetworkKeys to a new constructor
- Change unnecessary channel transfers (using notify)
=> Refactor giganto codes

giganto-client/src/publish.rs, src/publish.rs
struct 이름을 [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/naming.html#naming)를 따르도록 고쳤습니다.
giganto와 `PcapFilter`를 공유하는 `piglet`/`reconverge`도 수정이 필요하며,개별적으로 pcapfilter구조체를 정의하여 사용하는 hog 또한 이 구조체를 사용하도록 수정이 필요합니다.
=> Capitalize struct name in CamelCase

CHANGELOG.md, src/storage.rs
- Delete WAL with `set_max_total_wal_size`.
- Modify `target_file_size_multiplier` 1 to 10. By default, L1's sst has maximum about 51.2MB, L2's sst has maximum 512MB and so on.
- Set compression type to `Lz4`, bottommost compression type `Zstd` from default `Snappy` As recommendation from [Compression](https://github.com/facebook/rocksdb/wiki/Compression)
Issue: #280,
Issue: #283
이 PR은 compaction을 통해 sst 파일의 갯수와 용량 관리에 도움을 줄 수 있습니다.
하지만 이전의 db와 호환되지 않아 데이터를 새로 넣을 필요가 있습니다.
=> Modify db options

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/source.rs, src/ingest.rs, src/storage.rs
- Add `sources` query api returns source names.
```graphql
query sources {
sources
}
```
Issue: #294
=> Add sources graphql api

src/graphql/export.rs
rocksdb는 캡슐화 원칙에 따라 storage 모듈 내부에서만 사용하도록 하고 이외의 모듈에서는 사용하지 않도록 합니다.
=> Use rocksdb in storage module only

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
- Update giganto-client to 0.4.0.
- Add functionality to the graphql qeury to support the ftp protocol.
- Add functionality to the ingest and publish to support the ftp protocol.
Closes: #339
=> Support the Ftp Protocol

CHANGELOG.md, src/graphql/network.rs
https://github.com/aicers/giganto/pull/362 에서 추가한 api처럼 giganto가 지원하는 나머지 프로토콜을 대상으로 사용할 수 있는 api들을 추가합니다.
=> Add event search GraphQL API for protocols supported by giganto

src/ingest.rs
`send_ack_timestamp` is used by giganto only and not by any of giganto's clients, and thus should be removed from the giganto-client crate.
=> Use internal `send_ack_timestamp`

CHANGELOG.md, src/graphql.rs, src/graphql/status.rs, src/main.rs, src/settings.rs
기존의 setting은 argument의 설정이나 default 설정을 이용하도록 되어 있습니다. 그러나 실제 현재 현장에서 사용 되는 default 설정은 아래와 같습니다.
- giganto 설정 파일 : `usr/local/aice/conf/giganto.toml` 
- giganto 데이터 폴더 : `/data`
또한 graphql 의 `setGigantoConfig` 및 `reboot`을 할때 읽는 설정 파일의 위치는 고정값을 항상 사용하기 때문에, 만일 argument를 통해 giganto를 실행한 경우에는 실제 config 파일을 재 설정하지 않을 것입니다.
그렇기 때문에  1. 정확한 defautl 설정 값으로 수정  2. 실행시 참조한 설정 파일을 사용 하도록 수정하였습니다.
=> Add `cfg path` fields to Settings.

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/graphql/status.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/server.rs, src/settings.rs, tests/config.toml
- Add giganto's peers options to config file.
- Accepts QUIC connections from giganto's peers.
- Add the capability to exchange source and peer address lists between peers of the giganto.
- Change giganto's execution command.
Closes: #324 , #325
=> Add giganto clustering functionality

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs, src/storage.rs, src/storage/migration.rs
- Modify to handle network, log, and time series data requests with `ReqRange` and `RequestRange`.
- Add to handle `Timeseries` requests in `MessageCode::RawData`.
- Modify `multi_get_with_source` to return in the form of `Vec<(i64, String, Vec<u8>)>`.
- Bump version to 0.12.0
Closes: #435
Related issue: https://github.com/aicers/giganto-client/issues/32
=> Modify the processing part of REconverge's data request and release 0.12.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/main.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs, src/storage/migration.rs
- Supports the TLS protocol.
- Supports migration to versions 0.12.0 and earlier.
Closes: #437, #439
=> Add `tls` protocol and migration features

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs
Add benchmark statistics data to measure the hardware availability that Giganto runs.
=> generate benchmark statistics

src/ingest.rs
- the WAL buffer is flushed when it is full or giganto down.
Close: #541
=> Modify to execute flush when giganto down

CHANGELOG.md, Cargo.lock, src/ingest.rs, src/main.rs, src/peer.rs, src/publish.rs, src/storage.rs
- Add `--repair` option to the last argument to fix database.
- Change db option `max_background_jobs` to 6 from 2.
- Fix clippy error with rust 1.73.
=> Add repair database option

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage/migration.rs
giganto-client 디펜던시를 0.15.0 으로 올리면서 하위호환성이 깨지므로, 버전업을 수행합니다. 다음 사항이 핵심입니다.
- 0.15.0으로 버전 업데이트 합니다.
- min/max version을 수정합니다.
=> Release 0.15.0

CHANGELOG.md, src/publish.rs, src/publish/tests.rs
Change MessageCode::RawData processing code:
* Modified to send events in the same format as MessageCode::RangeData
REconverge request raw events for `Outliers` with the `MessageCode::RawData`, but the response raw events were  serialized structure instance values, so a problem occurred that could not be interpreted.
This PR modifies the response raw events to be sent in the same format as `MessageCode::RangeData`.
=> Change MessageCode::RawData request processing code

CHANGELOG.md, src/graphql.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs, src/web.rs
이슈에 기재된 것 이외에 통일성 관점에서 다음을 추가로 작업하였습니다.
1. main.rs에서 Arc<Notify> 류는 notify_xxxx 로 변경하였습니다. ( refer to : https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html)
2. StreamDirectChannel alias도 복수개의 아이템을 들고있는 Map 이므로, 복수형으로 변경하였습니다.
Resolves #596
=> Rename and relocate PacketSources, Sources, StreamDirectChannel

CHANGELOG.md, src/graphql.rs, src/graphql/status.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/settings.rs, tests/config.toml
- Set the `ack transmission count` by reading from the config file.
- Added `set_ack_transmission_count` GraphQL query for setting the ACK transmission count.
- Changed the data type of the ack transmission count in ingest from `const u16` to `AckTransmissionCount`.
Close: #612
=> Added features related to acknowledge transmission control

CHANGELOG.md, src/graphql.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
- Fix to initialize `ingest_sources` value from `sources` cf on giganto startup.
- Add `RunTimeIngestSources` type for store real-time connection source.
Close: #660
=> Fix for giganto ingest source

CHANGELOG.md, src/graphql.rs, src/graphql/client/schema/netflow5_raw_events.graphql, src/graphql/client/schema/netflow9_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/secu_log_raw_events.graphql, src/graphql/export.rs, src/graphql/netflow.rs, src/graphql/security.rs, src/ingest.rs
- Change the prefix of the db key in secuLog/netflow5/netflow9 to source.
- Modify the queries for that protocol based on the search through the source.
Close: #682
=> Modify db save key and related queries in secuLog/netflow5/netflow9

Cargo.lock, src/graphql/export.rs, src/graphql/log/tests.rs, src/storage.rs
- Bump chrono 0.4.34 to 0.4.35
- Modified `from_timestamp` with `DEFAULT_FROM_TIMESTAMP_NANOS` in `retain_periodically`
Close: #701
=> Bump dependencies

CHANGELOG.md, README.md, src/graphql/status.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish/tests.rs, src/server.rs, src/settings.rs, tests/certs/node1/config.toml
- Renamed configuration fields:
- `ingest_address` to `ingest_srv_addr`.
- `publish_address` to `publish_srv_addr`.
- `graphql_address` to `graphql_srv_addr`.
- Changed `roots` to `root` to handle using a single root.
Close: #710
=> Update configuration field names and handle single root usage

CHANGELOG.md, README.md, src/main.rs, src/settings.rs, src/storage.rs, tests/certs/node1/config.toml
- 이 pr에서는  rocksdb compaction 성능 향상을 위해 `increase_parallelism`/ `set_max_subcompactions` 옵션을 추가하였습니다.
- `increase_parallelism` 옵션은 rocksdb의 flush/ compaction 을 위한 thread 갯수를 설정 합니다. (기본: flush/compaction 각각 1 thread만 사용)
-  `set_max_subcompactions` 옵션은 rocksdb compaction시 해당 작업을 여러개로 분할하여 concurrently 하게 수행할 최대 thread 수를 설정합니다.(기본: 1 로 subcompaction 미사용을 의미)
- `increase_parallelism` / `set_max_subcompactions` 옵션을 적절히 줄 경우, compaction을 위한 background thread/ job이 증가하고,  compaction 작업을 분할해서 처리하게 되므로 compaction의 성능이 향상 될 것입니다.
Close: #732
=> Modify rocks opt to improve compaction performance

CHANGELOG.md, Cargo.lock, src/ingest/implement.rs, src/main.rs, src/publish/tests.rs
- Update rustls to version `0.21.12`.
- Update h2 to version `0.3.26`.
- Fix clippy warn/error.
Closes: #721 #726
=> Update dependency for security vulnerabilities

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/client/schema/conn_raw_events.graphql, src/graphql/client/schema/http_raw_events.graphql, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/ntlm_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/smtp_raw_events.graphql, src/graphql/client/schema/ssh_raw_events.graphql, src/graphql/client/schema/tls_raw_events.graphql, src/graphql/export.rs, src/graphql/export/tests.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/server.rs, src/storage.rs, src/storage/migration.rs, src/storage/migration/migration_structures.rs
- Update quinn, rustls version.
- Fixed code and structures based on changes to the conn, http, smtp, ntlm, ssh, tls protocols field.
- Update the compatibility version of the quic communication modules.
- Update the compatibility version for migration.
- Added migration function `migrate_0_19_to_0_21_0_alpha_1`.
Close: #730
=> Support giganto-client 0.17.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/client/derives.rs, src/graphql/client/schema/bootp_raw_events.graphql, src/graphql/client/schema/conn_raw_events.graphql, src/graphql/client/schema/dhcp_raw_events.graphql, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/search_bootp_raw_events.graphql, src/graphql/client/schema/search_dhcp_raw_events.graphql, src/graphql/export.rs, src/graphql/export/tests.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/graphql/statistics.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs, src/storage.rs, src/storage/migration.rs, src/storage/migration/migration_structures.rs
- Support bootp, dhcp events.
- Fix code and structures based on changes to the conn protocols field.
- Update the compatibility version of the quic communication modules.
- Update the compatibility version for migration.
- Add migration function `migrate_0_21_0_alpha_1_to_0_21_0_alpha_2`.
Close: #768
=> Support giganto-client 0.19.0

.github/workflows/ci.yml, CHANGELOG.md, src/graphql.rs, src/graphql/export.rs, src/graphql/export/tests.rs, src/graphql/log.rs, src/graphql/log/tests.rs, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/graphql/packet.rs, src/graphql/security.rs, src/graphql/source.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/graphql/sysmon.rs, src/graphql/timeseries.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs, src/server.rs, src/settings.rs, src/storage.rs, src/storage/migration.rs, src/web.rs
- Apply `group_imports=StdExternalCrate` format.
- Fix clippy error.
Related issue: #760
=> Apply rustfmt's option `group_imports=StdExternalCrate`

CHANGELOG.md, docs/guide-giganto-cluster-graphql.md, src/graphql.rs, src/graphql/client/schema/conn_raw_events.graphql, src/graphql/client/schema/dce_rpc_raw_events.graphql, src/graphql/client/schema/dns_raw_events.graphql, src/graphql/client/schema/ftp_raw_events.graphql, src/graphql/client/schema/http_raw_events.graphql, src/graphql/client/schema/kerberos_raw_events.graphql, src/graphql/client/schema/ldap_raw_events.graphql, src/graphql/client/schema/mqtt_raw_events.graphql, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/nfs_raw_events.graphql, src/graphql/client/schema/ntlm_raw_events.graphql, src/graphql/client/schema/rdp_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/smb_raw_events.graphql, src/graphql/client/schema/smtp_raw_events.graphql, src/graphql/client/schema/ssh_raw_events.graphql, src/graphql/client/schema/tls_raw_events.graphql, src/graphql/log.rs, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/graphql/packet.rs, src/graphql/security.rs, src/graphql/sysmon.rs, src/ingest/implement.rs, src/storage.rs
- Add `NetworkOptFilter` struct to allow network event search queries to request all sources.
- Add functions for all source search.
- Change the sorting of event search results for all sources to timestamp, source.
- Modify network event search queries.
- Change the type of filter from `NetworkFilter` to `Option<NetworkOptFilter>`.
- Add `request_from_peer` as a parameter to the queries.
- Change the `paged_events_in_cluster` macro argument to handle all source requests.
- Add the source field to the network event search result structure.
Close: #770
=> Support for all sources in network protocol search queries

CHANGELOG.md, README.md, src/graphql.rs, src/graphql/client/schema/schema.graphql, src/graphql/status.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/settings.rs, tests/certs/node1/config.toml
close: #786 
close: #787 
#786 을 작업하고 test 를 돌려보는 도중 #787 이슈를 만났고, 이에 대한 fix도 함께 넣었습니다. 두가지 작업은 별개의 commit으로 작성하였습니다.
---
#787 이슈의 발생 원인으로는 모종의 원인(아마도 rust 1.80 업데이트와 관련이 있을 것으로 추측합니다)에 의하여 함수 scope를 벗어날 때 raw fd를 인자로 하는 `unsafe` 함수로 생성된 `file` 이 먼저 drop 되고, 그 다음 `temp_file` 이 drop 되는 순서가 발생하는 것으로 생각하고 있습니다. 우리가 `write_run_tcpdump`에서 `savefile_raw_fd` 함수로 달성하고자 하는 바는 safe 함수로도 충분히 가능하므로 아래와 같은 변경을 반영하고자 합니다.
=> Rename giganto cluster related configs & Remove `unsafe` block in `write_run_tcpdump`

CHANGELOG.md, docs/guide-giganto-cluster-graphql.md, src/graphql.rs, src/graphql/client/derives.rs, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/total_count.graphql, src/graphql/export.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/graphql/packet.rs, src/graphql/sysmon.rs
Add `total_count` GraphQL query & Remove unsafe block in `write_run_tcpdump`
- Add `total_count` GraphQL query to return the number of events for a specific filter condition.
- Fix `events_in_cluster` macro.
- Add `into` expression to also support `total_count` query.
- Add macro pattern to return the sum of all source request results.
- Removed `unsafe` block in `write_run_tcpdump` while creating a temorary file.
Related issue: #787
Close: #790
=> Add `total_count` GraphQL query & Remove unsafe block in `write_run_tcpdump`

CHANGELOG.md, src/graphql.rs, src/graphql/client/schema/schema.graphql, src/graphql/export.rs, src/graphql/network.rs, src/storage.rs
- Changed `sourceId` in `ExportFilter` to `Option<String>`.
- Modified network protocol's RawEvent struct to extract json and csv formats.
- Added `Serialize` and use the `#[serde(serialize_with)]` attribute.
- Implement `Display` trait.
- Added `process_export_for_all_source` to handle extraction for all sources.
Close: #778
=> Supports exporting files for all sources of network protocol events

CHANGELOG.md, Cargo.toml, src/graphql/client/derives.rs, src/graphql/client/schema/schema.graphql, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/graphql/statistics.rs, src/graphql/sysmon.rs, src/lib.rs
Close #619
Add macro `from_key_value_with_str_num_fields`.
- `plain_field`: A field that remains unchanged without any type conversion.
- `str_num_field`: A field that is converted to the `StringNumber` type.
=> Use `StringNumber` for integers beyond `i32` in a GraphQL API

.github/workflows/ci.yml
close: #816
To me it seems like codecov works well with the updated ci.yml.
=> Use codecov token

README.md
Retrieving badge.svg from codecov does not require a token.
=> Remove unnecessary codecov token from README.md

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage/migration.rs
- Updated dependency for security vulnerabilities.
- Update the compatibility version of the quic communication modules.
Related issue: #849
=> Bump version to 0.22.0

CHANGELOG.md, src/graphql.rs, src/graphql/export.rs, src/ingest.rs, src/main.rs, src/publish.rs
- Fix `Connection` of type `PcapSources` to `Vec<Connection>`. This change will allow giganto to find the latest `Connection` and extract pcap even if it detects a late disconnect from ingest.
- Apply the log level based on the RUST_LOG.
- Fix clippy error.
Close: #859
Close: #860
=> Fix `Connection` of type `PcapSources` to `Vec<Connection>`

CHANGELOG.md, src/graphql.rs, src/graphql/status.rs, src/main.rs, src/peer.rs, src/settings.rs
- Changed GraphQL APIs `config` and `setConfig` to return an error when using local configuration.
- Removed the GraphQL API `setAckTransmissionCount`
Closes: #854 
Closes: #866 
Closes: #870
=> Use remote configuration directly

src/graphql.rs
In the `check_address` function, we were cloning the `start` and `end` fields of the `IpRange` struct. However, since we only need to dereference these fields to parse them as `IpAddr`, we can use `as_deref` instead of cloning.
=> Remove unnecessary `clone`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/client/schema/op_log_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/export/tests.rs, src/graphql/log.rs, src/graphql/log/tests.rs, src/ingest.rs, src/ingest/generation.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs, src/storage/migration.rs, src/storage/migration/migration_structures.rs
Close #724
The RocksDB keys in the `oplog` are currently in the form agent_id-0-timestamp. This change modifies the keys to the form timestamp-sequence.
=> Change `OpLogFilter::agent_id` to be optional

src/graphql.rs, src/graphql/export.rs, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/security.rs, src/graphql/statistics.rs, src/graphql/sysmon.rs, src/publish.rs, src/storage.rs
=> Resolve clippy errors after Rust update

src/main.rs
This changes the type of `ONE_DAY` constant from `u64` to `Duration`. Since `Duration` is a more specific and descriptive type that clearly conveys the unit of time being represented, it reduces the likelihood of bugs.
=> Improve type safety

src/graphql/export.rs, src/graphql/statistics.rs, src/lib.rs, src/main.rs, src/peer.rs, src/publish.rs, src/publish/implement.rs, src/storage.rs, src/storage/migration.rs
=> Refactor unwrap to improve error handling

src/ingest.rs, src/peer.rs, src/publish.rs, src/server.rs
This pull request removes unnecessary `Arc` wrappers from various parts of the codebase. This change aims to simplify the codebase and reduce unnecessary overhead.
=> Remove unnecessary `Arc` wrappers

CHANGELOG.md, src/graphql.rs, src/graphql/status.rs, src/main.rs, src/storage.rs, src/web.rs
- If `log_dir` is not present in the local/remote config, logs are written to stdout/stderr.
- If `log_dir` in the local/remote config is writable, logs are written to the specified `log_dir`.
- If `log_dir` in the local config is not writable, the program terminates.
- If `log_dir` in the remote config is not writable, the program enters idle mode.
- Logging in idle mode: logs are written to stdout/stderr until the remote config is retrieved.
Close: #878
=> Adjust logging behavior by revised logging policy

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
Closes: #979 ;
Adds documentation for `DceRpcRawEvent` in schema and other related files.
=> Add documentation for `DceRpcRawEvent`

README.md, src/graphql.rs
Added a missing comma in the README.md file.
Closes #1033
=> Correct the format of `--ca-certs` CLI argument

.cargo/config.toml, .gitignore, CHANGELOG.md, README.md, src/main.rs
Renamed the log file from giganto.log to data_store.log.
Added the env variable `LOG_FILE_NAME` to the Cargo config file.
Closes #1047
=> Rename the log file

CHANGELOG.md, src/graphql.rs, src/graphql/export.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/sysmon.rs, src/ingest.rs, src/lib.rs, src/main.rs, src/peer.rs, src/publish.rs
~This draft PR has been opened to document the code used for pcap extraction, which we plan to verify with this commit. It is not yet ready for review, as it is intended solely to share the exact extraction method used.~
Related: #888 
Closes: #1065 
Based on commit e96e4ad in this PR, testing was conducted on the test server, and I have confirmed that PCAP data is successfully served via the GraphQL API. The testing was conducted in both single-queue and multi-queue packet parsing modes. The CI failure with e96e4ad is lint failure from Clippy, which was updated to 1.86.0 very recently. The Clippy fix is addressed in the last commit of this PR. The lint check is now passing. So I convert this draft PR to a regular pull request.
---
Note: Since this PR might not be sufficient to fully …
=> Limit PCAP dump to first 10 packets

CHANGELOG.md, src/main.rs
- close #1075
- Previously, logging behavior depended on both `log_path` and the build type(debug/release).
- Removed the dependency on the build type.
- Logging is now controlled solely by `log_path`.
=> Change logging behavior to depend on log_path

Cargo.lock, Cargo.toml, src/settings.rs
Testing confirms that an invalid `export_dir` results in a GraphQL error, leaving exception handling to the user, who is then responsible for updating the incorrect value.
Closes #1083
=> Remove unnecessary validation from `ConfigVisible`

CHANGELOG.md, src/graphql.rs, src/graphql/network/tests.rs
- Modify `check_address` and `check_port` to ensure consistent search range boundaries for time, address, and port.
(There are no additional modifications needed beyond the current changes in the codebase.)
Close: #1098
=> Ensure consistent search range boundary handling

src/graphql/network.rs, src/graphql/sysmon.rs
This reduces the processing time of `cargo fmt` from minutes to sub-second.
Fixes #1122.
=> Flatten deeply-nested expressions

CHANGELOG.md, Cargo.lock, Cargo.toml, src/comm/ingest.rs, src/comm/ingest/tests.rs, src/comm/peer.rs, src/comm/publish.rs, src/comm/publish/tests.rs, src/graphql/client/schema/ftp_raw_events.graphql, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/export.rs, src/graphql/export/tests.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/storage/migration.rs, src/storage/migration/migration_structures.rs
Closes #1156
- Modify FTP event structure to store all commands as `Vec<FtpCommand>` instead of single command fields
- Implement manual From trait conversions for `FtpCommandRawEvent` to handle GraphQL client type conversions
- Update cluster mode tests to query commands array structure (`commands { fileSize }` instead of direct `fileSize`)
- Ensure compatibility with giganto-client's updated FTP structure (rev=f52f942)
- Modified FTP event structure to store multiple commands as `Vec<FtpCommand>`
instead of single command fields. This change preserves the complete command
history of FTP sessions, enabling better threat analysis and session tracking.
The FTP GraphQL API now returns a `commands` array containing all commands
and their responses from a session.
=> Refactor FTP event structure to store commands
