aicers/giganto

Cargo.lock, Cargo.toml, src/ingestion.rs, src/main.rs
=> Add QUIC Server

.github/workflows/ci.yml
=> Skip integration tests in CI

src/ingestion.rs, src/main.rs, src/settings.rs
=> Set Server address via config file

src/ingestion.rs, src/main.rs, src/settings.rs
=> Config Cert directory

Cargo.lock, Cargo.toml, src/ingestion.rs, tests/ingestion.rs
- Modify send data form (test)
- Parse receive data
- Print record type/timestamp
Resolves: #4
=> Print received Data

Cargo.lock, Cargo.toml, src/ingestion.rs, tests/ingestion.rs
Closes #13, Closes #20, Closes #21
=> Check receive Conn, DNS, Log

src/ingestion.rs, src/storage.rs
=> Add Httpconn, Rdpconn

README.md, src/storage.rs, tests/ingestion.rs
-Add http,rdp test function
-Modify READM.md (for http,Rdp content)
-Modify column const array (add http,rdp)
=> Add test fucntions

src/graphql.rs, src/ingestion.rs, src/main.rs, src/storage.rs
=> Add GraphQL conn

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/settings.rs, src/storage.rs, tests/config.toml
=> Delete old information

src/ingestion.rs
`Arc::clone` is no longer needed since `Database` now implements
`Clone`.
=> Remove redundant `Arc`

Cargo.lock, Cargo.toml, src/graphql.rs, src/ingestion.rs, src/storage.rs, tests/ingestion.rs
Add src_raw_events to given source
Close #35, Close #37
=> Add graphql log, modify conn

README.md, src/ingestion.rs, src/storage.rs, tests/ingestion.rs
=> Send Ack Message

src/graphql.rs, src/ingestion.rs
=> Add dnsRawEvents

src/ingestion.rs
Since giganto now stores all the received data into the storage, it is no longer necessary to print them.
=> Remove printing received data

src/graphql.rs, src/ingestion.rs
=> Add httpRawEvents

src/graphql.rs, src/ingestion.rs, src/storage.rs
=> Update log key

Cargo.lock, Cargo.toml, src/ingestion.rs, src/main.rs
=> Use tracing to print message

src/ingestion.rs, src/settings.rs, src/web.rs, tests/common.rs
=> Print correct error message 

src/graphql.rs, src/ingestion.rs
=> Add rdpRawEvents

src/storage.rs
=> Modify retain logic

src/graphql.rs, src/ingestion.rs, src/storage.rs
- Input key separator
- Unify RawEventstore functions (append,raw_event)
- Change raw_event method as generic
Fixes: #70
=> Modify key value struct

src/main.rs, src/publish.rs, src/settings.rs, tests/config.toml
=> Add QUIC server for sending data

Cargo.lock, Cargo.toml, src/graphql.rs, src/storage.rs
=> Add time range for dnsRawEvents

src/graphql.rs, src/storage.rs
=> Add log cursor

src/storage.rs
=> Return correct event given source

src/graphql.rs
=> Change return type to async error

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs
=> Refactor graphql module

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/storage.rs
=> Add cursor for all queries

src/ingestion.rs, src/main.rs, src/publish.rs, src/settings.rs
This simplifies codes running servers.
=> Parse addresses during config parsing

Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/ingestion.rs
=> Add unit tests

src/ingestion.rs, src/main.rs, src/publish.rs, src/web.rs
This handles cert/key loading once to remove redundant cert/key handling in different modules.
=> Remove redundant arguments

src/main.rs, src/web.rs
=> Fix web key to pem

.github/workflows/ci.yml, README.md, tests/ingestion.rs
=> Add code coverage

src/storage.rs
=> Add a function to return an iterator for log

CHANGELOG.md, src/ingestion.rs
=> Add compitable version check communication

src/ingestion.rs, src/publish.rs
=> Send certain period of log to publish module

src/ingestion.rs
- Reqeust current timstamp data
- Response sended data
- Modify tick channel buffer size
Closes: #101
=> Add quic command channel

src/graphql.rs, src/ingestion.rs
=> Add maximum page size

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/publish.rs, src/storage.rs
=> Fix boundary conditions for pagination

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingestion.rs, tests/common.rs
=> Release 0.2.0

src/graphql/log.rs
GraphQL API에서 시간 범위 조건이 들어가는 경우의 테스트 케이스입니다. 커서가 없고 `start`와 `end`만 주어진 경우인데, 일단 이 테스트들이 통과하게 되면 커서가 있는 경우도 비슷하게 테스트를 만들 필요가 있습니다.
=> Add tests for retrieving raw events in the given time range

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/ingestion.rs
=> Add timestamp for graphql

CHANGELOG.md, src/graphql/log.rs, src/ingestion.rs, src/storage.rs, tests/ingestion.rs
+ Restruct Ingestion::Log
Close: #125
=> Add periodic time series

CHANGELOG.md, src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/ingestion.rs
=> Add filtering to graphql

CHANGELOG.md, src/graphql.rs, src/ingestion.rs, src/publish.rs, tests/common.rs, tests/ingestion.rs
- Add Request/Response log message logic
- Add handshake logic
Closes: #126, Closes: #132
=> Add publish protocol logic

src/graphql.rs, src/graphql/network.rs, src/ingestion.rs
=> Fix filter range

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs
=> Reconstruct separating the filter structure

src/graphql/network.rs
=> Refactory impl FromKeyValue through macro

src/storage.rs
=> Change api called by flush function

CHANGELOG.md, src/ingestion.rs, src/publish.rs, src/storage.rs, tests/ingestion.rs
=> Add period time series message logic

CHANGELOG.md, Cargo.lock, src/ingestion.rs
=> Release 0.3.0

src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/ingestion.rs, src/publish.rs, src/storage.rs
This reducues code redundancy and simplifies generic parameters.
=> Merge iterator functions for raw events

CHANGELOG.md, src/graphql/log.rs, src/ingestion.rs, src/main.rs, src/publish.rs, src/server.rs, src/storage.rs
- Separate compatible versions of ingestion/publish
- Extract common functions of ingestion/publish
- Remove storage module gen_key function.
Closes: #157
=> Refactor ingestion/publish logic

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/ingestion.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
=> Add network stream logic

CHANGELOG.md, src/graphql.rs, src/graphql/network.rs, src/ingestion.rs, src/server.rs, src/storage.rs
- Add network union type
- Modify expect to controlflow and add close connection delay to REproduce (https://github.com/aicers/reproduce/pull/159)
Close: #155, Fix: #162
=> Add network union type

CHANGELOG.md, src/ingestion.rs
- Add req/resp processing logic for the corresponding PR(https://github.com/aicers/reproduce/pull/159)
=> Add channel finish logic for one-shot log event.

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingestion.rs, src/ingestion/tests.rs, src/publish.rs, src/publish/tests.rs
- Update quinn 0.8 to 0.9
See: #165,
Close: #164
=> Release 0.4.0

src/publish.rs
=> Add else to prevent panic on select

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/network.rs, src/ingestion.rs, src/publish/tests.rs, src/storage.rs
- Receives SMTP events from Piglet
- Enables to query for SMTP events
- Adds `answer` field to DNS event
=> Receives and query for SMTP events

Cargo.lock, Cargo.toml, src/ingestion.rs, src/publish.rs, src/server.rs
=> Modify protocol compare logic

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/log.rs, src/graphql/network.rs, src/ingestion.rs, src/ingestion/tests.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
=> Release 0.5.0

src/ingestion.rs, src/ingestion/tests.rs, src/storage.rs
- Modify time series receive data format
- Modify time series storage format
Closes: #175
=> Modify time series format

src/publish.rs, src/publish/tests.rs
- Modify request message format
- Modify Modify stream-related functions
Closes: #174
=> Modify network stream logic

CHANGELOG.md, src/ingestion.rs, src/publish.rs, src/publish/tests.rs
=> Add publish protocol request/response logic

src/ingestion.rs, src/publish.rs, src/publish/tests.rs
- Add timeseries storage struct
- Modify publish request/response logic about time series
- Modify ack timestamp interval value
Closes: #191
=> Fix timeseries publish logic

CHANGELOG.md, src/graphql.rs, src/graphql/timeseries.rs, src/ingestion.rs
=> Add timeseries graphql api

CHANGELOG.md, src/graphql/network.rs, src/ingestion.rs, src/publish/tests.rs
* DNS answer 필드에 도메인 이름을 저장할 수 있도록 Type을 String으로 수정합니다.
=> change dns answer field to string

src/graphql/network.rs, src/ingestion.rs, src/ingestion/network.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
- `Ntlm`, `Kerberos`, `Ssh`, `DceRpc` 
- testcode not implemented
Close: #198
=> Add network protocols

CHANGELOG.md, src/graphql/network.rs, src/ingestion/tests.rs, src/publish/tests.rs
=> Add testcode for more data types

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingestion.rs, src/ingestion/tests.rs, src/publish.rs
=> Release 0.6.0

src/graphql.rs, src/graphql/packet.rs, src/ingestion.rs, src/ingestion/tests.rs, src/main.rs
=> Remove static variable from the ingestion module

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingestion/tests.rs, src/publish.rs, src/publish/tests.rs
- Send start message
- Add test functions
Closes: #213
=> Send different stream start message depending on the daemon

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/main.rs, src/settings.rs, tests/config.toml
=> Save giganto's syslog

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/log.rs, src/graphql/network.rs, src/graphql/timeseries.rs, src/ingestion.rs, src/ingestion/log.rs, src/ingestion/network.rs, src/ingestion/tests.rs, src/main.rs, src/server.rs, src/storage.rs
- Modify tracing
- Add oplog store
- Add oplog to GraphQL
- Add filter to oplog ( agentId: program@source, logLevel: Info, Warn, Error )
Issue: #218
=> Add operation log

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/graphql.rs, src/graphql/export.rs, src/graphql/network.rs, src/ingestion.rs, src/ingestion/log.rs, src/ingestion/network.rs, src/main.rs, src/publish.rs, src/settings.rs, tests/config.toml
=> Add database file export graphql function

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingestion.rs, src/ingestion/tests.rs, src/publish.rs, src/publish/tests.rs
=> Release 0.7.0

src/graphql/export.rs, src/graphql/log.rs, src/ingestion.rs, src/storage.rs
- Remove duplicated test code in export
=> Add oplog to export

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/network.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
=> Add more dns field

CHANGELOG.md, README.md, src/main.rs
* Check write permission of `/data/logs/apps/giganto.log`
* Fix to write to syslog file only INFO or higher level message
=> Check write permission of syslog file

CHANGELOG.md, src/graphql/export.rs, src/graphql/network.rs, src/ingest/network.rs, src/publish/tests.rs
=> Add more http fields

giganto-client/src/publish.rs, giganto-client/src/publish/range.rs, giganto-client/src/publish/stream.rs, src/main.rs, src/publish.rs, src/publish/tests.rs
=> Add pcap extract request/response logic

CHANGELOG.md, giganto-client/src/ingest.rs, src/ingest.rs, src/storage.rs
- Store packet
- Key has req_source, req_time, packet_time
Issue: #247
=> Add packet store

Cargo.lock, giganto-client/Cargo.lock, giganto-client/Cargo.toml, giganto-client/src/publish.rs, src/publish.rs
=> Modify ack for request

giganto-client/src/publish.rs, giganto-client/src/publish/stream.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs
- Add direct stream condition
- Modify giganto-client's hog/crusher stream functions
=> Modify publish stream logic

src/graphql.rs, src/graphql/export.rs, src/graphql/packet.rs, src/ingest.rs, src/ingest/tests.rs, src/publish.rs
- PacketFilter takes request time as nanos (i64)
- Modify ingest packet
Fix: #256
=> Modify packet process

giganto-client/src/frame.rs, giganto-client/src/ingest.rs, giganto-client/src/publish.rs, src/publish.rs
- Add receive Ok/Err function (for giganto/reconverge/hog usage)
- Add Hash trait to RecordType enum (for piglet usage)
=> Modify giganto-client function/enum

giganto-client/src/lib.rs
Need test with associated module
Close: #264
=> Modify nanoseconds 

giganto-client/src/connection.rs, src/ingest.rs, src/publish.rs
- Add bool `is_reproduce`
Issue: #268
=> Modify server handshake

src/graphql/network.rs
- Add protocols.
- Fix infinite loop when direction is backward.
=> Modify network raw events

src/publish.rs
=> Modify PCAP request processing to be done in a thread

CHANGELOG.md, README.md, src/graphql.rs, src/ingest/tests.rs, src/main.rs, src/publish/tests.rs, src/settings.rs, src/storage.rs
- Add cf options.
- Modify db open method to enable cf options.
- Add cf options to config file
todo:
- additional options
- docs of config options
Issue: #280
=> Modify database options

src/storage.rs
- Modify stat dump period 10min to 1 hour.
- keep info log file numbers max 10.
=> Modify db info log options

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/status.rs
=> Add GraphQL API for giganto's resource status

src/ingest.rs
현재 piglet이 실행중일 때  reproduce가 접속 시 `packet_sources`에 덮어쓰지 않지만 (#269)
reproduce연결이 끊어질 때 piglet의 연결을 끊는 버그가 있어 추가 수정합니다.
관련 이슈에 따라 추후 인증서에 따라 재 수정이 될 수 있습니다.
- Duplicated source name deleted from packet sources
Issue: #268
=> Fix packet sources

src/graphql/status.rs, src/storage.rs
- Estimate live data size in cf
- Estimate number of keys in cf
- Show stats of cf
```graphql
query prop {
propertiesCf(filter: { recordType: "log"}) {
estimateLiveDataSize,
estimateNumKeys
stats
}
}
```
디버그 중 데이터 확인을 편하게 하기 위해 GraphQL API 로 만들었는데
각 Column family 마다 데이터 사이즈와 몇개가 저장되어있는지 대략적인 값을 알 수 있어 관리 기능 추가 혹은 관리에 유용합니다.
=> Add cf properties to graphql api

CHANGELOG.md, Cargo.lock, src/graphql.rs, src/graphql/status.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/publish.rs, src/publish/tests.rs, src/server.rs, src/storage.rs, src/web.rs
- config file의 변경을 giganto에 적용하기 위해서 변경이 일어난 경우 자체적으로 SIGUP signal 발생 및 수신하여 giganto를 재시작합니다.
Issue: #295
=> Add Giganto restart signal processing

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
- Update `ingest`, `publish` version to 0.8.0.
Release Issue: #334
=> Release 0.8.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
=> Release 0.9.0

CHANGELOG.md, src/main.rs, src/storage.rs
=> Add giganto db version compatibility check

CHANGELOG.md, Cargo.lock, Cargo.toml, src/publish.rs, src/publish/tests.rs, src/storage.rs
- Add multi_get returns source, value.
Close: #347
=> Add publish api to return raw events

src/storage/migration.rs
https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
=> Use a semicolon if nothing returned

src/graphql/export.rs
This commit replaces the `convert_time_format` function used from the giganto-client crate with a proprietary format conversion routine within giganto. This decision stems from the impending protocol changes in giganto-client, which will transition from text to binary event format.
The time format used by giganto-client is dependent on the communication protocol, which is subject to change, thereby making the time format unreliable for giganto's needs.
On the contrary, giganto's time format is intended for data export, adhering to Zeek's format, and thus requires a more stable and self-controlled conversion routine. This change ensures giganto's time format remains consistent and unaffected by any external modifications in the giganto-client crate.
=> Replace convert_time_format function dependency

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
=> Release 0.10.1

src/publish.rs
`send_crusher_stream_start_message` and `send_crusher_data` are used by giganto only and not by any of giganto's clients, and thus should be removed from the giganto-client crate.
=> Use internal `send_crusher_*`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
=> Support mqtt protocol

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
=> Release 0.10.2

src/graphql/status.rs
=> Fix release bug

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
=> Support LDAP protocol & Modified Fields.

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest/tests.rs, src/publish/tests.rs
=> Release 0.12.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs, src/storage.rs
=> Add `smb`/`nfs` protocols and release 0.12.2

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/export.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/status.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish/tests.rs
- Fix fields of `FtpRawEvent`, `FtpJsonOutput`.
- Fix warning in status.rs when build to release.
- Modified `collect_records` to continue collecting even if error
data is included in the data.
=> Fix `FtpRawEvent`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/packet.rs, src/main.rs
=> Modify `pcap_with_data` test function to compare times based on timezone

.github/cache-cargo/action.yml, .github/workflows/ci.yml
Use a build cache to speed up builds.
=> Add build cache script

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/export.rs, src/graphql/statistics.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/storage/migration.rs
pending aicers/giganto-client#58
Add `core` id to the key of `Statistics` store.
* Add GraphQL query for `Statistics` store.
* Change `export` query to support `Statistics` store.
=> add core id to the key of statistics store

src/graphql/sysmon.rs
- Added `agent_name` and `agent_id` fields.
Close: #501
=> Add fields to sysmon graphql

Cargo.lock, Cargo.toml, src/graphql/network.rs, src/graphql/status.rs, src/peer.rs, src/publish.rs, src/server.rs, src/storage/migration.rs, src/web.rs
=> Add sysmon event to publish stream data

src/graphql/packet.rs
- Fixed to convert local timezone to UTC without affecting DST.
Close: #398
=> Modify the `pcap_with_data` test function

CHANGELOG.md, Cargo.lock, src/graphql/export.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/statistics.rs, src/ingest/tests.rs, src/publish/tests.rs, src/storage.rs, src/storage/migration.rs
=> Release 0.13.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/export/netflow.rs, src/graphql/network.rs, src/ingest.rs, src/ingest/implement.rs, src/publish.rs, src/storage.rs
=> add netflow v5, v9 event

CHANGELOG.md, Cargo.lock, src/graphql.rs, src/graphql/security.rs, src/storage.rs
- Modify agentId to source
- Add contents filter
- Fix retain bug.
=> Fix seculog filter

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage/migration.rs
=> Release 0.14.0

.gitignore, Cargo.lock, Cargo.toml, src/graphql/export.rs, src/graphql/log.rs, src/graphql/security.rs, src/graphql/statistics.rs, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/storage.rs
related to #576
depend on https://github.com/aicers/giganto-client/pull/77 & https://github.com/aicers/giganto-client/pull/79
=> Update giganto-client to 0.15.0 (#576)

.github/workflows/ci.yml
=> Increase CI fd ulimit to 8096

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/network.rs
If a user inputs a single IP or port then search those events only
=> Change ip range and port range to be close ends search

CHANGELOG.md, src/graphql.rs, src/graphql/statistics.rs, src/storage.rs
=> Replace manual boundary check by BoundaryIter with `iterator_cf_opt`

CHANGELOG.md, src/graphql/network.rs, src/graphql/sysmon.rs, src/publish.rs, src/storage.rs
성능 측정: [Giganto Multi_get 성능 측정](https://www.notion.so/cluml/de29733dbb7742f5810a8390c72d53e0?pvs=4#867658d248d14dbe86ed545086ed7bf3)
Close: #597
=> Change to use `batched_multi_get_cf` for multi get search

CHANGELOG.md, Cargo.lock, src/storage.rs
- When disk usage exceeds `USAGE_THRESHOLD`, delete old data until disk usage is reduced to `USAGE_LOW`.
- Supports all column families.
- The iterator stops processing data once it encounters data that is newer than the specified retention period.
=> Modify `retain_periodically`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/network.rs, src/graphql/sysmon.rs
R프로젝트 진행에 필요한 기능이라 해당 기능에 대해 merge 및 release를 동시에 진행 합니다.
=> Added `sysmon_events` query to search for all sysmon event & release 0.15.4

CHANGELOG.md, src/storage.rs
- Stop retain when db has no more data.
=> Fix retention

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql.rs, src/graphql/client/schema/schema.graphql, src/graphql/export.rs, src/graphql/log.rs, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/security.rs, src/graphql/timeseries.rs, src/ingest/implement.rs, src/peer.rs, src/publish.rs, src/storage.rs, src/storage/migration.rs
- R 프로젝트의 Branch로 관리되던 부분 중 Giganto의 main에 포함될 수 있는 agent_id 필터링 기능을 pr합니다.
=> Added filtering for `agent_id` in GraphqlQL query

CHANGELOG.md, Cargo.lock
=> Release 0.15.4+tis.0.0.1

CHANGELOG.md, src/graphql/export.rs
=> Modify to set to the extension that matches the export type

CHANGELOG.md, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/network.rs, src/graphql/network/tests.rs
=> Added SmtpRawEvent to NetworkRawEvents Union Graphql Query

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/sysmon.rs, src/ingest.rs, src/ingest/implement.rs, src/storage.rs
This PR is for a feature that is only used in rio projects.
=> Support pe file protocol

CHANGELOG.md
=> Add missing release dates

CHANGELOG.md, Cargo.lock, Cargo.toml, src/peer.rs, src/publish.rs, src/storage/migration.rs
=> Add migration for versions below 0.19.0

.gitignore, CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs
1. Implemented suggested code changes to ensure proper logging:
- In release build mode, logs are written exclusively to a file.
- In debug build mode, logs are written both to stdout and a file.
2. Removed the unnecessary line: `deleted tracing_subscriber::fmt::init();`
=> Refine logging configuration

CHANGELOG.md, Cargo.lock, Cargo.toml, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs
=> Branch off `tis` from 0.19.0 & cherry-pick tis project content

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release `0.19.0+tis.0.1.0`

src/ingest.rs, src/peer.rs, src/publish.rs, src/storage.rs
=> Add log message to show running or fail status exactly

CHANGELOG.md, Cargo.lock, README.md, src/graphql.rs, src/graphql/client/schema/schema.graphql, src/graphql/export.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/source.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/graphql/sysmon.rs, src/main.rs, src/storage.rs
- Support ping, stop, reboot(linux), shutdown(linux)
- if `retain_periodically` is running, waits for the `retain_flag` to turn false.
#295
=> Update remote node control

CHANGELOG.md, src/graphql/export.rs
=> Added the `.export` tag to the file being exported

CHANGELOG.md, src/graphql/status.rs, src/main.rs
=> Use temporary file to `set_giganto_config`

Cargo.lock, Cargo.toml, src/graphql/log/tests.rs, src/graphql/network/tests.rs, src/graphql/packet.rs, src/graphql/security.rs, src/graphql/source.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/graphql/timeseries.rs, src/peer.rs, src/storage.rs
- Modify the associated code based on the crate's versioning of dependencies.
=> Bump dependencies

CHANGELOG.md, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs
Apply to `Tis` branch.
Receive events in a unit of 100.
Discussion https://github.com/aicers/giganto/discussions/671
Pending aicers/piglet#767
Compatible REproduce - https://github.com/aicers/reproduce/tree/tis
Compatible Piglet - https://github.com/aicers/piglet/tree/tis
=> Receive events in a unit of 100

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage/migration.rs
=> Release 0.20.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/implement.rs, src/ingest/tests.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs
- Branch off from 0.20.0.
- Add request stream/send stream url collector.
- Receive events in a unit of 100 for protocol events or 10 for packets.
Close: #746
=> Branch off `tis` from 0.20.0 & cherry-pick tis project content

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.20.0+tis.0.2.0

CHANGELOG.md, src/graphql/export.rs
=> Add a kind value to the extract filename

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/client/schema/bootp_raw_events.graphql, src/graphql/client/schema/network_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/export.rs, src/graphql/export/tests.rs, src/graphql/network.rs, src/graphql/network/tests.rs, src/ingest/tests.rs, src/publish/tests.rs
=> Rename `chwaddr` to `chaddr`

Cargo.lock, Cargo.toml
Fix for: Remove unnecessary dependency #781
=> Remove humantime

src/main.rs, src/peer.rs, src/server.rs
modify funtion - certificate_info_default
add param : print_client_name
Close #789
=> Fix misleading log 

CHANGELOG.md, src/storage/migration.rs, src/storage/migration/migration_structures.rs
remove
- migrate_0_10_to_0_12
- migrate_0_12_to_0_13_0
Close #794
=> Remove migration code less than 0.15.3

src/ingest.rs, src/main.rs, src/peer.rs, src/publish.rs, src/server.rs
modify function
certificate_info_default -> subject_from_cert_opt
subject_from_cert, subject_from_cert_verbose
Close #800
=> Rename the public methods related to certificates

CHANGELOG.md, src/graphql.rs
=> Change `MAXIMUM_PAGE_SIZE` to 300

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest/tests.rs, src/peer.rs, src/publish/tests.rs, src/server.rs
=> Modify to use ring as the rustls cryptography library option

CHANGELOG.md
=> Update CHANGELOG to graphql api names

CHANGELOG.md
=> Update CHANGELOG to graphql api names for tis

CHANGELOG.md, src/graphql.rs, src/graphql/status.rs, src/settings.rs
Closed #819
Closed #820
Remove unnecessary "Giganto" prefix
Change `setConfig` to return `Result<bool>`
=> Remove unnecessary "Giganto" prefix

CHANGELOG.md
=> Correct items of CHANGELOG

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs, src/storage/migration.rs, src/storage/migration/migration_structures.rs
related to #823
close #836 
This PR is related to two issues, since #836 and #823 cannot be easily split into separate PRs, mainly because #836 could be considered as a subset task of #823.
=> Release 0.21.0

src/graphql/status.rs
=> Remove configuration details from info macro

CHANGELOG.md, Cargo.lock, src/graphql.rs, src/graphql/status.rs, src/main.rs, src/settings.rs
=> Update `config` to include local information

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest/tests.rs, src/peer.rs, src/publish/tests.rs
=> Bump version to 0.22.1

CHANGELOG.md, src/main.rs
=> Modify the repair mode

src/graphql/status.rs
Strings can be directly converted into `toml_edit::Value`.
=> Remove redundant `if`

CHANGELOG.md, src/graphql/client/derives.rs, src/graphql/client/schema/csv_formatted_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/log.rs, src/graphql/log/tests.rs
- Add GraphQL API `csvFormattedRawEvents` that returns the values of raw events of the request protocol in csv format String.
Close: #896
=> Add GraphQL API `csvFormattedRawEvents`

CHANGELOG.md, src/graphql/status.rs
=> Update `setConfig` GraphQL API

src/graphql/status.rs
This PR removes unnecessary `clone` calls in `src/graphql/status.rs`.
=> Remove unnecessary `clone`s

CHANGELOG.md, src/graphql/client/derives.rs, src/graphql/client/schema/csv_formatted_raw_events.graphql, src/graphql/client/schema/schema.graphql, src/graphql/client/schema/tsv_formatted_raw_events.graphql, src/graphql/log.rs, src/graphql/log/tests.rs
Related comment: https://github.com/aicers/giganto/pull/897#issuecomment-2489931613
=> Rename `csvFormattedRawEvents` to `tsvFormattedRawEvents`

CHANGELOG.md, src/peer.rs
=> Improve CHANGELOG for 0.23.0

src/publish.rs
Introduced a macro `handle_store!` to encapsulate the common logic for handling different store types.
=> Refactor process_stream function to reduce repetition

CHANGELOG.md, src/ingest.rs, src/ingest/tests.rs, src/publish.rs, src/publish/tests.rs
=> Fix `INGEST_VERSION_REQ` and `PUBLISH_VERSION_REQ`

.github/workflows/ci.yml, src/graphql.rs, src/graphql/export/tests.rs, src/graphql/log/tests.rs, src/graphql/network/tests.rs, src/graphql/packet.rs, src/graphql/sensor.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/ingest/tests.rs, src/peer.rs, src/publish/tests.rs, src/storage/migration.rs
Updated CI configuration to include Clippy checks for tests.
Close: #932
=> Resolve Clippy errors in test code

docs/guide-giganto-cluster-graphql.md, src/graphql.rs, src/graphql/log.rs, src/graphql/netflow.rs, src/graphql/network.rs, src/graphql/packet.rs, src/graphql/security.rs, src/graphql/sensor.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/graphql/sysmon.rs, src/graphql/timeseries.rs, src/ingest/tests.rs, src/peer.rs, src/publish.rs, src/publish/tests.rs
=> Fix Clippy warning caused by rustc 1.84.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/graphql/log/tests.rs, src/publish.rs, src/publish/implement.rs, src/publish/tests.rs
=> Use public names for external modules

src/lib.rs, src/main.rs
- Refactor unwrap_or_else to explicitly handle errors instead of returning default values.
Close: #955
=> Refactor `unwrap_or_else`

CHANGELOG.md, src/graphql/status.rs
=> Update `retention` format in `config` GraphQL API

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `FtpRawEvent`

CHANGELOG.md, README.md, src/graphql/status.rs, src/main.rs, src/settings.rs
=> Change the `log_dir` type to `Option<PathBuf>`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `HttpRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `KerberosRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `MqttRawEvent`

CHANGELOG.md, docs/guide-giganto-cluster-graphql.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `NfsRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `LdapRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `SmbRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `TlsRawEvent`

src/graphql/network.rs
=> Correct the GraphQL Documentation

src/graphql/client/schema/schema.graphql
=> Generate schema.graphql file

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `SshRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `SmtpRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `BootpRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `DhcpRawEvent`

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `RdpRawEvent`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/graphql.rs, src/graphql/client/schema/schema.graphql, src/graphql/network.rs, src/graphql/status.rs, src/ingest.rs, src/ingest/tests.rs, src/main.rs, src/peer.rs, src/publish.rs, src/settings.rs, src/storage.rs, src/web.rs, tests/config.toml
=> Modify configuration management

CHANGELOG.md, src/graphql/client/schema/schema.graphql, src/graphql/network.rs
=> Add documentation for `NtlmRawEvent`

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/peer.rs, src/publish.rs, src/storage/migration.rs
=> Bump version to 0.24.0

CHANGELOG.md, README.md, src/graphql/status.rs, src/settings.rs, tests/config.toml
=> Set default GraphQL API port to 8443

src/graphql/status.rs
=> Change datalake to data store

.cargo/config.toml, src/main.rs
=> Rename the env variable

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version to 0.24.1

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version to 0.24.2

README.md
=> Refactor README with Markdown rules

CHANGELOG.md, src/main.rs, src/settings.rs
=> Add backup and restore configuration on failure

README.md
=> Remove unnecessary `<!-- markdownlint-disable -->`

src/graphql/export.rs
=> Fix clippy error for Rust 1.87.0

src/peer.rs
=> Rename `local_hostname` in `peer`

CHANGELOG.md, Cargo.lock, Cargo.toml
Issue #1094 
- Updating the bincode crate will be covered in a separate issue
- No changes to the COMPATIBLE version are required.
=> Release 0.24.3

src/storage.rs
=> Improve logging for database cleanup

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ingest.rs, src/peer.rs, src/publish.rs, src/storage/migration.rs
Issue #1116 
- Updating the bincode crate will be covered in a separate issue
=> Release 0.25.0

src/comm/ingest.rs, src/comm/peer.rs, src/comm/publish.rs, src/graphql.rs, src/graphql/export.rs, src/graphql/statistics.rs, src/graphql/status.rs, src/main.rs, src/storage.rs, src/storage/migration.rs, src/web.rs
Closes: #1134
Notable:
- Removed internally-used name(giganto) from log messages to improve readability.
=> Refactor log messages for consistency and clarity

src/comm/ingest.rs, src/comm/peer.rs, src/comm/publish.rs, src/graphql.rs, src/graphql/export.rs, src/graphql/packet.rs, src/graphql/status.rs, src/main.rs, src/web.rs
=> Add logs for audit purposes

src/comm/ingest.rs, src/graphql.rs, src/graphql/client/derives.rs, src/graphql/export.rs, src/lib.rs, src/server.rs, src/storage.rs
=> Fix clippy error for Rust 1.89.0

Cargo.lock, Cargo.toml
=> Prevent using mixed TLS backends

.github/workflows/ci.yml
=> Generate code coverage with default feature
